name: Send Gift
on:
  workflow_dispatch:
  schedule:
    - cron: '*/20 * * * *'

jobs:
  troll_job:
    runs-on: ubuntu-latest
    strategy:
      # Это заставит GitHub создать 20 копий этой задачи
      matrix:
        machine: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
      # Если одна машина упадет с ошибкой, остальные продолжат работать
      fail-fast: false
      # Сколько запускать одновременно (максимум 20 для Free аккаунта)
      max-parallel: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Generate Fake Video
        run: |
          ffmpeg -f lavfi -i color=c=red:s=640x480:d=35 -vf "drawtext=text='ЗДАРОВА ЛОХ':fontcolor=white:fontsize=50:x=(w-text_w)/2:y=(h-text_h)/2" -pix_fmt yuv420p video.y4m

      - name: Run Bot
        # Можно даже передать номер машины в скрипт, если нужно (через переменную окружения)
        env:
          MACHINE_ID: ${{ matrix.machine }}
        run: python bot.py
